package core;

import java.util.Random;

/**
 * A random name generator that creates names by combining a prefix and a suffix
 * from two specified files.
 */
public class NameGenerator
{
    // FIELDS
    
    /** The array of all syllables to choose from. */
    private String[][] syllables;
    
    /** The random number generator used to select prefixes and suffixes. */
    private Random random;
    
    // CONSTRUCTORS
    
    /**
     * Creates a NameGenerator with the given syllable sets and the given random
     * generator.
     * @param syllables the syllables to choose from
     * @param random the random generator to use
     */
    public NameGenerator(String[][] syllables, Random random)
    {
        this.syllables = syllables;
        this.random = random;
    }
    
    /**
     * Creates a NameGenerator with the given syllable sets and a new random
     * generator with the given seed.
     * @param syllables the syllables to choose from
     * @param seed the seed of the random generator to use
     */
    public NameGenerator(String[][] syllables, long seed)
        {this(syllables, new Random(seed));}
    
    /**
     * Creates a NameGenerator with the given syllable sets and a new random
     * generator.
     * @param syllables the syllables to choose from
     */
    public NameGenerator(String[][] syllables)
        {this(syllables, new Random());}
    
    /**
     * Creates a NameGenerator with the given file names and the given random
     * generator.
     * @param files the paths of the files to load
     * @param random the random generator to use
     */
    public NameGenerator(String[] files, Random random)
    {
        syllables = new String[files.length][];
        for (int syllable = 0; syllable < files.length; syllable++)
            syllables[syllable] = FileManager.toLineArray(files[syllable]);
        this.random = random;
    }
    
    /**
     * Creates a NameGenerator with the given file names and a new random
     * generator with the given seed.
     * @param files the paths of the files to load
     * @param seed the seed of the random generator to be used
     */
    public NameGenerator(String[] files, long seed)
        {this(files, new Random(seed));}
    
    /**
     * Creates a NameGenerator with the given file names and a new random
     * generator.
     * @param files the paths of the files to load
     */
    public NameGenerator(String[] files)
        {this(files, new Random());}
    
    // GENERATION
    
    /**
     * Retrieves a random syllable from the given place in the array.
     * @param place the index of the syllable array to choose from
     * @return a randomly-selected String from the place in the syllable array
     */
    public String getSyllable(int place)
    {
        if (place < 0 || place >= syllables.length ||
                syllables == null || syllables[place] == null)
            return null;
        
        return syllables[place][random.nextInt(syllables[place].length)];
    }
    
    /**
     * Generates a random name with the given number of syllables.
     * @param length the number of syllables that will be in the generated name
     * @return a name generated by combining the given number of syllables
     */
    public String generateName(int length)
    {
        if (length <= 0 || length > syllables.length)
            return null;
        
        StringBuilder name = new StringBuilder();
        for (int place = 0; place < length; place++)
            name.append(getSyllable(place));
        return name.toString();
    }
    
    /**
     * Generates a random name with a random number of syllables above the lower
     * bound.
     * @param min the fewest number of syllables that will be chosen
     * @return a name generated by combining a random number of syllables above
     * the lower bound
     */
    public String generateRandomLengthName(int min)
    {
        return generateName(Math.min(random.nextInt(syllables.length)
                + Math.max(min, 1), syllables.length));
    }
    
    /**
     * Generates a random name with a random number of syllables.
     * @return a name generated by combining a random number of syllables
     */
    public String generateRandomLengthName()
        {return generateName(random.nextInt(syllables.length) + 1);}
    
    /**
     * Generates a random name by combining the maximum number of ordered
     * syllables.
     * @return a name generated by combining a syllable from each possible place
     */
    public String generateFullName()
        {return generateName(syllables.length);}
}